// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { default as StateUsa } from './StateUsa';

/** Identifier type for public.business */
export type BusinessId = string & { __brand: 'BusinessId' };

/**
 * PUBLIC:
 * Represents the table public.business
 */
export default interface BusinessTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<BusinessId, BusinessId | undefined, BusinessId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  address: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  address_line_2: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  city: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  zip_code: ColumnType<string | null, string | null, string | null>;

  /** Database type: public.state_usa */
  state: ColumnType<StateUsa | null, StateUsa | null, StateUsa | null>;

  /** Database type: pg_catalog.text */
  county: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  email: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  name_display: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  name_legal: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  duns: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  dba: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  tin: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  phone: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  business_type: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  industry: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.date */
  date_business_began: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  /** Database type: pg_catalog.float8 */
  revenue_average: ColumnType<number | null, number | null, number | null>;

  /** Database type: pg_catalog.float8 */
  debt: ColumnType<number | null, number | null, number | null>;
}

export type Business = Selectable<BusinessTable>;

export type NewBusiness = Insertable<BusinessTable>;

export type BusinessUpdate = Updateable<BusinessTable>;
