// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { BusinessId } from './Business';
import type { UserId } from './User';

/** Identifier type for public.business_user */
export type BusinessUserId = string & { __brand: 'BusinessUserId' };

/**
 * PUBLIC:
 * Represents the table public.business_user
 */
export default interface BusinessUserTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<BusinessUserId, BusinessUserId | undefined, BusinessUserId>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.uuid */
  business_id: ColumnType<BusinessId, BusinessId, BusinessId>;

  /** Database type: pg_catalog.uuid */
  user_id: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.text */
  job_title: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.float8 */
  owernship: ColumnType<number | null, number | null, number | null>;

  /** Database type: pg_catalog.float8 */
  income_average_monthly: ColumnType<
    number | null,
    number | null,
    number | null
  >;

  /** Database type: pg_catalog.float8 */
  expense_average_monthly: ColumnType<
    number | null,
    number | null,
    number | null
  >;
}

export type BusinessUser = Selectable<BusinessUserTable>;

export type NewBusinessUser = Insertable<BusinessUserTable>;

export type BusinessUserUpdate = Updateable<BusinessUserTable>;
