// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * PUBLIC:
 * Represents the enum public.environment_type
 */
enum EnvironmentType {
  production = 'production',
  uat = 'uat',
}

export default EnvironmentType;
