// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { OrganizationId } from './Organization';
import type { UserId } from './User';

/** Identifier type for public.organization_user */
export type OrganizationUserId = string & { __brand: 'OrganizationUserId' };

/**
 * PUBLIC:
 * Represents the table public.organization_user
 */
export default interface OrganizationUserTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<
    OrganizationUserId,
    OrganizationUserId | undefined,
    OrganizationUserId
  >;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.varchar */
  organization_id: ColumnType<OrganizationId, OrganizationId, OrganizationId>;

  /** Database type: pg_catalog.uuid */
  user_id: ColumnType<UserId, UserId, UserId>;
}

export type OrganizationUser = Selectable<OrganizationUserTable>;

export type NewOrganizationUser = Insertable<OrganizationUserTable>;

export type OrganizationUserUpdate = Updateable<OrganizationUserTable>;
