// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { OrganizationId } from './Organization';
import type { BusinessId } from './Business';

/** Identifier type for public.organization_business */
export type OrganizationBusinessId = string & {
  __brand: 'OrganizationBusinessId';
};

/**
 * PUBLIC:
 * Represents the table public.organization_business
 */
export default interface OrganizationBusinessTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<
    OrganizationBusinessId,
    OrganizationBusinessId | undefined,
    OrganizationBusinessId
  >;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.varchar */
  organization_id: ColumnType<OrganizationId, OrganizationId, OrganizationId>;

  /** Database type: pg_catalog.uuid */
  business_id: ColumnType<BusinessId, BusinessId, BusinessId>;
}

export type OrganizationBusiness = Selectable<OrganizationBusinessTable>;

export type NewOrganizationBusiness = Insertable<OrganizationBusinessTable>;

export type OrganizationBusinessUpdate = Updateable<OrganizationBusinessTable>;
