// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { default as EnvironmentType } from './EnvironmentType';

/** Identifier type for public.organization */
export type OrganizationId = string & { __brand: 'OrganizationId' };

/**
 * PUBLIC:
 * Represents the table public.organization
 */
export default interface OrganizationTable {
  /** Database type: pg_catalog.varchar */
  id: ColumnType<OrganizationId, OrganizationId, OrganizationId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.varchar */
  clerk_id: ColumnType<string, string, string>;

  /** Database type: public.environment_type */
  environment_type: ColumnType<
    EnvironmentType,
    EnvironmentType | undefined,
    EnvironmentType
  >;
}

export type Organization = Selectable<OrganizationTable>;

export type NewOrganization = Insertable<OrganizationTable>;

export type OrganizationUpdate = Updateable<OrganizationTable>;
