// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserTable } from './User';
import type { default as BusinessTable } from './Business';
import type { default as OrganizationTable } from './Organization';
import type { default as OrganizationUserTable } from './OrganizationUser';
import type { default as BusinessUserTable } from './BusinessUser';
import type { default as OrganizationBusinessTable } from './OrganizationBusiness';

export default interface PublicSchema {
  user: UserTable;

  business: BusinessTable;

  organization: OrganizationTable;

  organization_user: OrganizationUserTable;

  business_user: BusinessUserTable;

  organization_business: OrganizationBusinessTable;
}
