// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { default as StateUsa } from './StateUsa';

/** Identifier type for public.user */
export type UserId = string & { __brand: 'UserId' };

/**
 * PUBLIC:
 * Represents the table public.user
 */
export default interface UserTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<UserId, UserId | undefined, UserId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  address: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  address_line_2: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  city: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  zip_code: ColumnType<string | null, string | null, string | null>;

  /** Database type: public.state_usa */
  state: ColumnType<StateUsa | null, StateUsa | null, StateUsa | null>;

  /** Database type: pg_catalog.text */
  county: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  clerk_id: ColumnType<string, string, string>;

  /** Database type: pg_catalog.varchar */
  email: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  phone: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.varchar */
  ssn: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.date */
  date_of_birth: ColumnType<
    Date | null,
    Date | string | null,
    Date | string | null
  >;

  /** Database type: pg_catalog.int4 */
  credit_score: ColumnType<number | null, number | null, number | null>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
