// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as PublicSchema } from './Public/PublicSchema';
import type { default as TenantBaseOrgSchema } from './TenantBaseOrg/TenantBaseOrgSchema';

type Database = PublicSchema & TenantBaseOrgSchema;

export default Database;
