// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { UserId } from '../Public/User';

import type { OpportunityId } from './Opportunity';
import type { DealStatusId } from './DealStatus';

/** Identifier type for tenant_base_org.deal */
export type DealId = string & { __brand: 'DealId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.deal
 */
export default interface DealTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<DealId, DealId | undefined, DealId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  label: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.text */
  source: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.int4 */
  winnability: ColumnType<number | null, number | null, number | null>;

  /** Database type: pg_catalog.int4 */
  appetite: ColumnType<number | null, number | null, number | null>;

  /** Database type: pg_catalog.int4 */
  ssbs_score: ColumnType<number | null, number | null, number | null>;

  /** Database type: pg_catalog.numeric */
  loan_amount: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.numeric */
  interest_rate: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.numeric */
  loan_processing_fee: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.uuid */
  opportunity_id: ColumnType<OpportunityId, OpportunityId, OpportunityId>;

  /** Database type: pg_catalog.varchar */
  status_id: ColumnType<DealStatusId, DealStatusId, DealStatusId>;

  /** Database type: pg_catalog.uuid */
  assignee_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  /** Database type: pg_catalog.uuid */
  created_by_id: ColumnType<UserId | null, UserId | null, UserId | null>;
}

export type Deal = Selectable<DealTable>;

export type NewDeal = Insertable<DealTable>;

export type DealUpdate = Updateable<DealTable>;
