// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for tenant_base_org.deal_status */
export type DealStatusId = string & { __brand: 'DealStatusId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.deal_status
 */
export default interface DealStatusTable {
  /** Database type: pg_catalog.varchar */
  id: ColumnType<DealStatusId, DealStatusId, DealStatusId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.varchar */
  label: ColumnType<string, string, string>;

  /** Database type: pg_catalog.int4 */
  order: ColumnType<number | null, number | null, number | null>;
}

export type DealStatus = Selectable<DealStatusTable>;

export type NewDealStatus = Insertable<DealStatusTable>;

export type DealStatusUpdate = Updateable<DealStatusTable>;
