// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { UserId } from '../Public/User';
import type { BusinessId } from '../Public/Business';

import type { DealId } from './Deal';

/** Identifier type for tenant_base_org.opportunity */
export type OpportunityId = string & { __brand: 'OpportunityId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.opportunity
 */
export default interface OpportunityTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<OpportunityId, OpportunityId | undefined, OpportunityId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.uuid */
  active_deal_id: ColumnType<DealId | null, DealId | null, DealId | null>;

  /** Database type: pg_catalog.text */
  label: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.uuid */
  assignee_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  /** Database type: pg_catalog.uuid */
  borrower_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  /** Database type: pg_catalog.uuid */
  borrower_business_id: ColumnType<
    BusinessId | null,
    BusinessId | null,
    BusinessId | null
  >;

  /** Database type: pg_catalog.uuid */
  created_by_id: ColumnType<UserId | null, UserId | null, UserId | null>;
}

export type Opportunity = Selectable<OpportunityTable>;

export type NewOpportunity = Insertable<OpportunityTable>;

export type OpportunityUpdate = Updateable<OpportunityTable>;
