// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * PUBLIC:
 * Represents the enum tenant_base_org.property_type
 */
enum PropertyType {
  commercial = 'commercial',
  residential = 'residential',
}

export default PropertyType;
