// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for tenant_base_org.task_status */
export type TaskStatusId = number & { __brand: 'TaskStatusId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.task_status
 */
export default interface TaskStatusTable {
  /** Database type: pg_catalog.int4 */
  id: ColumnType<TaskStatusId, TaskStatusId, TaskStatusId>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.varchar */
  label: ColumnType<string, string, string>;
}

export type TaskStatus = Selectable<TaskStatusTable>;

export type NewTaskStatus = Insertable<TaskStatusTable>;

export type TaskStatusUpdate = Updateable<TaskStatusTable>;
