// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

import type { UserId } from '../Public/User';

import type { TaskStatusId } from './TaskStatus';
import type { TaskPriorityId } from './TaskPriority';
import type { DealId } from './Deal';

/** Identifier type for tenant_base_org.task */
export type TaskId = string & { __brand: 'TaskId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.task
 */
export default interface TaskTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<TaskId, TaskId | undefined, TaskId>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.int4 */
  status_id: ColumnType<TaskStatusId, TaskStatusId | undefined, TaskStatusId>;

  /** Database type: pg_catalog.int4 */
  priority_id: ColumnType<
    TaskPriorityId,
    TaskPriorityId | undefined,
    TaskPriorityId
  >;

  /** Database type: pg_catalog.text */
  title: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  description: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.uuid */
  assignee_id: ColumnType<UserId | null, UserId | null, UserId | null>;

  /** Database type: pg_catalog.uuid */
  deal_id: ColumnType<DealId, DealId, DealId>;
}

export type Task = Selectable<TaskTable>;

export type NewTask = Insertable<TaskTable>;

export type TaskUpdate = Updateable<TaskTable>;
