// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for tenant_base_org.task_priority */
export type TaskPriorityId = number & { __brand: 'TaskPriorityId' };

/**
 * PUBLIC:
 * Represents the table tenant_base_org.task_priority
 */
export default interface TaskPriorityTable {
  /** Database type: pg_catalog.int4 */
  id: ColumnType<TaskPriorityId, TaskPriorityId, TaskPriorityId>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.varchar */
  label: ColumnType<string, string, string>;
}

export type TaskPriority = Selectable<TaskPriorityTable>;

export type NewTaskPriority = Insertable<TaskPriorityTable>;

export type TaskPriorityUpdate = Updateable<TaskPriorityTable>;
