// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as DealStatusTable } from './DealStatus';
import type { default as OpportunityTable } from './Opportunity';
import type { default as DealTable } from './Deal';
import type { default as TaskStatusTable } from './TaskStatus';
import type { default as TaskPriorityTable } from './TaskPriority';
import type { default as TaskTable } from './Task';
import type { default as PropertyTable } from './Property';
import type { default as DealUserTable } from './DealUser';
import type { default as ViewOrganizationUserTable } from './ViewOrganizationUser';
import type { default as ViewOrganizationBusinessTable } from './ViewOrganizationBusiness';

export default interface TenantBaseOrgSchema {
  deal_status: DealStatusTable;

  opportunity: OpportunityTable;

  deal: DealTable;

  task_status: TaskStatusTable;

  task_priority: TaskPriorityTable;

  task: TaskTable;

  property: PropertyTable;

  deal_user: DealUserTable;

  view_organization_user: ViewOrganizationUserTable;

  view_organization_business: ViewOrganizationBusinessTable;
}
