// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable } from 'kysely';

import type { UserId } from '../Public/User';
import type { default as StateUsa } from '../Public/StateUsa';

/**
 * PUBLIC:
 * Represents the view tenant_base_org.view_organization_user
 */
export default interface ViewOrganizationUserTable {
  /** Database type: pg_catalog.uuid */
  id: ColumnType<UserId, never, never>;

  /** Database type: pg_catalog.text */
  external_id: ColumnType<string, never, never>;

  /** Database type: pg_catalog.timestamptz */
  created_at: ColumnType<Date, never, never>;

  /** Database type: pg_catalog.timestamptz */
  updated_at: ColumnType<Date, never, never>;

  /** Database type: pg_catalog.text */
  address: ColumnType<string, never, never>;

  /** Database type: pg_catalog.text */
  address_line_2: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  city: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  zip_code: ColumnType<string, never, never>;

  /** Database type: public.state_usa */
  state: ColumnType<StateUsa, never, never>;

  /** Database type: pg_catalog.text */
  county: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  clerk_id: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  email: ColumnType<string, never, never>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  phone: ColumnType<string, never, never>;

  /** Database type: pg_catalog.varchar */
  ssn: ColumnType<string, never, never>;

  /** Database type: pg_catalog.date */
  date_of_birth: ColumnType<Date, never, never>;

  /** Database type: pg_catalog.int4 */
  credit_score: ColumnType<number, never, never>;
}

export type ViewOrganizationUser = Selectable<ViewOrganizationUserTable>;
